version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  nodeapp:
    image: node-app:01
    container_name: node-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:example@mongo-db:27017/userDB?authSource=admin
      PORT: 3000
    depends_on:
      - mongo

volumes:
  mongo-data:
